apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-user
  labels:
    name: sc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sc-user
  template:
    metadata:
      name: sc-user
      labels:
        name: sc-user
    spec:
      containers:
        - name: sc-user
          image: jdimasw/sc-user
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: sc-user-service
spec:
  type: NodePort
  selector:
    name: sc-user
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000